

/*
document DOC1 and DOC2 are document reference number coming from ui

*/

const docContants = {
    "TemplatePath":'C:/work/hackaton/eagle-appdocs-backend/template/',
   "OutputPath":'C:/work/hackaton/eagle-appdocs-backend/Output/',
    "doc1":'cre_commitment_letter_v3.docx',
   "doc2":'Res_ACP_Commitment_Ltr.docx',
    "outDoc1":'cre_commitment_letter_out_v3.docx',
    "outDoc2":'test1_out.docx'
}

const OpenDBinfo1 =
[
    {
      "Loannumber": "500532",
      "Borrower1FirstName": "John",
      "Borrower1LastName": "Doe",
      "PropType": "Condo",
      "PropAddress1": "111 Pine St",
      "PropAddress2": "Suite1800",
      "PropCity": "San Francisco",
      "PropState": "CA",
      "PropZip": "94111"
    },
    {
      "Loannumber": "500533",
      "Borrower1FirstName": "Jane",
      "Borrower1LastName": "Doe",
      "PropType": "PUD",
      "PropAddress1": "1 Front St",
      "PropAddress2": "Floor 7",
      "PropCity": "San Francisco",
      "PropState": "CA",
      "PropZip": "94111"
    },
    {
      "Loannumber": "500534",
      "Borrower1FirstName": "Andy",
      "Borrower1LastName": "America",
      "PropType": "SFR",
      "PropAddress1": "388 Market St",
      "PropAddress2": "Room 14G",
      "PropCity": "San Francisco",
      "PropState": "CA",
      "PropZip": "94111"
    }
  ]





  const OpenDBinfo =[
    {
      "Field": "Entry 1",
      "Loannumber": "500532",
      "Borrower1FirstName": "John",
      "Borrower1MiddleName": "A.",
      "Borrower1LastName": "Doe",
      "Borrower1SSN": "111-22-3333",
      "Borrower2FirstName": "Jane",
      "Borrower2MiddleName": "B.",
      "Borrower2LastName": "Doe",
      "Borrower1SSN__1": "444-55-6666",
      "Vesting": "John and Jane Doe",
      "Guarantor1FirstName": "Mark",
      "Guarantor1MiddleName": "C.",
      "Guarantor1LastName": "Purchaser",
      "Guarantor2FirstName": "Megan",
      "Guarantor2MiddleName": "D.",
      "Guarantor2LastName": "Purchaser",
      "AccountFirstName": "Josh",
      "AccountMiddleName": "M.",
      "AccountLastName": "Tester",
      "Closer": "Julia Closer",
      "CloserTitle": "Manager",
      "CloserPhone": "(800) 000-1111",
      "PropType": "Condo",
      "MailingAddress1": "1 Mailing St",
      "MailingAddress2": "Apt. 111",
      "MailingCity": "San Francisco",
      "MailingState": "CA",
      "MailingZip": "94111",
      "PropAddress1": "111 Pine St",
      "PropAddress2": "Suite1800",
      "PropCity": "San Francisco",
      "PropCounty": "San Francisco",
      "PropState": "CA",
      "PropZip": "94111",
      "LoanType": "Purchase",
      "SalesPrice": "$1,500,000",
      "LoanAmount": "$1,000,000",
      "TotalCost": "$900,000",
      "LoanAmountTyped": "One Million Dollars",
      "AppraisedAmount": "$1,000,000",
      "AppraisalPercent": "50%",
      "MaxLTV": "80%",
      "LoanTerm": "30",
      "LoanTermMonths": "360",
      "ConstructionTerm": "6",
      "Amortization": "ARM",
      "IOTerm": "120",
      "InitialInterestRate": "4.50%",
      "Margin": "0.50%",
      "InterestRate": "5.00%",
      "Index": "Prime",
      "FixedPeriod": "36",
      "ClosingMonth": "January",
      "InterestRateAdjustment": "Monthly",
      "Ceiling": "14%",
      "Floor": "2.00%",
      "PrepayTerm": "10th",
      "PrepayLimit": "20.00%",
      "AssumptionPercent": "50%",
      "LoanFeePercent": "1.00%",
      "DocFee": "$600",
      "CommitmentTerm": "2/9/2020",
      "LateCharge": "10.00%",
      "DefaultClauseRate": "0.25%",
      "DebtCoverageRatio": "80.00%",
      "CoverageAmount": "$1,000,000.00",
      "SignDate": "12/25/2019",
      "CommitmentFee": "$1,000",
      "AccountNo": "1234567890",
      "ArchitectName": "Bruce Banner",
      "ArchitectCompany": "Hulk Architects",
      "ArchitectAddressLine1": "1 Arch St",
      "ArchitectCity": "San Francisco",
      "ArchitectState": "CA",
      "ArchitectZip": "94111",
      "Today": "12/11/2019"
    },
    {
      "Field": "Entry 2",
      "LoanNumber": "07023456",
      "Borrower1FirstName": "John",
      "Borrower1MiddleName": "E.",
      "Borrower1LastName": "Homeowner",
      "Borrower1SSN": "222-33-4444",
      "Borrower2FirstName": "Mary",
      "Borrower2MiddleName": "F.",
      "Borrower2LastName": "Homeowner",
      "Borrower1SSN__1": "555-66-7777",
      "Vesting": "John and Mary Homeowner",
      "Guarantor1FirstName": "Jason",
      "Guarantor1MiddleName": "G.",
      "Guarantor1LastName": "Guarantor",
      "Guarantor2FirstName": "Jane",
      "Guarantor2MiddleName": "H.",
      "Guarantor2LastName": "Guarantor",
      "AccountFirstName": "Angelina",
      "AccountMiddleName": "N.",
      "AccountLastName": "Loaner",
      "Closer": "James Closer",
      "CloserTitle": "Closer",
      "CloserPhone": "(800) 111-2222",
      "PropType": "PUD",
      "MailingAddress1": "1 Test Dr",
      "MailingAddress2": "Apt. 222",
      "MailingCity": "San Francisco",
      "MailingState": "CA",
      "MailingZip": "94111",
      "PropAddress1": "1 Front St",
      "PropAddress2": "Floor 7",
      "PropCity": "San Francisco",
      "PropCounty": "San Francisco",
      "PropState": "CA",
      "PropZip": "94111",
      "LoanType": "Refinance",
      "SalesPrice": "",
      "LoanAmount": "$500,000",
      "TotalCost": "$400,000",
      "LoanAmountTyped": "Five Hundred Thousand Dollars",
      "AppraisedAmount": "$500,000",
      "AppraisalPercent": "80%",
      "MaxLTV": "75%",
      "LoanTerm": "20",
      "LoanTermMonths": "240",
      "ConstructionTerm": "9",
      "Amortization": "Fixed",
      "IOTerm": "60",
      "InitialInterestRate": "3.25%",
      "Margin": "0.75%",
      "InterestRate": "4.00%",
      "Index": "WSJ",
      "FixedPeriod": "24",
      "ClosingMonth": "February",
      "InterestRateAdjustment": "Quarterly",
      "Ceiling": "12%",
      "Floor": "2.25%",
      "PrepayTerm": "9th",
      "PrepayLimit": "15.00%",
      "AssumptionPercent": "40%",
      "LoanFeePercent": "1.50%",
      "DocFee": "$700",
      "CommitmentTerm": "2/9/2020",
      "LateCharge": "15.00%",
      "DefaultClauseRate": "0.50%",
      "DebtCoverageRatio": "70.00%",
      "CoverageAmount": "$2,000,000.00",
      "SignDate": "12/25/2019",
      "CommitmentFee": "$2,000",
      "AccountNo": "2345678901",
      "ArchitectName": "Captain America",
      "ArchitectCompany": "Captain Design",
      "ArchitectAddressLine1": "1 Design Ave",
      "ArchitectCity": "San Francisco",
      "ArchitectState": "CA",
      "ArchitectZip": "94111",
      "Today": "12/11/2019"
    },
    {
      "Field": "Entry 3",
      "LoanNumber": "07034567",
      "Borrower1FirstName": "Andy",
      "Borrower1MiddleName": "I.",
      "Borrower1LastName": "America",
      "Borrower1SSN": "333-44-5555",
      "Borrower2FirstName": "Amy",
      "Borrower2MiddleName": "J.",
      "Borrower2LastName": "America",
      "Borrower1SSN__1": "666-77-8888",
      "Vesting": "Andy and Amy Ameica",
      "Guarantor1FirstName": "Alan",
      "Guarantor1MiddleName": "K.",
      "Guarantor1LastName": "Buyer",
      "Guarantor2FirstName": "Ann",
      "Guarantor2MiddleName": "L.",
      "Guarantor2LastName": "Buyer",
      "AccountFirstName": "Kent",
      "AccountMiddleName": "O.",
      "AccountLastName": "Clark",
      "Closer": "Bruce Wayne",
      "CloserTitle": "Closing Manager",
      "CloserPhone": "(800) 222-3333",
      "PropType": "SFR",
      "MailingAddress1": "2 Mailing St",
      "MailingAddress2": "Suite 1800",
      "MailingCity": "San Francisco",
      "MailingState": "CA",
      "MailingZip": "94111",
      "PropAddress1": "388 Market St",
      "PropAddress2": "Room 14G",
      "PropCity": "San Francisco",
      "PropCounty": "San Francisco",
      "PropState": "CA",
      "PropZip": "94111",
      "LoanType": "Purchase",
      "SalesPrice": "$500,000",
      "LoanAmount": "$250,000",
      "TotalCost": "$225,000",
      "LoanAmountTyped": "Two Hundred Fifty Thousand Dollars",
      "AppraisedAmount": "$250,000",
      "AppraisalPercent": "25%",
      "MaxLTV": "70%",
      "LoanTerm": "15",
      "LoanTermMonths": "180",
      "ConstructionTerm": "12",
      "Amortization": "ARM",
      "IOTerm": "24",
      "InitialInterestRate": "4.75%",
      "Margin": "0.25%",
      "InterestRate": "5.00%",
      "Index": "12MAT",
      "FixedPeriod": "12",
      "ClosingMonth": "March",
      "InterestRateAdjustment": "Semi-Annually",
      "Ceiling": "10%",
      "Floor": "2.50%",
      "PrepayTerm": "8th",
      "PrepayLimit": "10.00%",
      "AssumptionPercent": "30%",
      "LoanFeePercent": "2.00%",
      "DocFee": "$800",
      "CommitmentTerm": "2/9/2020",
      "LateCharge": "20.00%",
      "DefaultClauseRate": "0.75%",
      "DebtCoverageRatio": "60.00%",
      "CoverageAmount": "$3,000,000.00",
      "SignDate": "12/25/2019",
      "CommitmentFee": "$3,000",
      "AccountNo": "3456789012",
      "ArchitectName": "Anthony Edward Stark",
      "ArchitectCompany": "Stark Enterprise",
      "ArchitectAddressLine1": "1 Architect Lane",
      "ArchitectCity": "San Francisco",
      "ArchitectState": "CA",
      "ArchitectZip": "94111",
      "Today": "12/11/2019"
    },
    {
      "Field": "",
      "LoanNumber": "",
      "Borrower1FirstName": "",
      "Borrower1MiddleName": "",
      "Borrower1LastName": "",
      "Borrower1SSN": "",
      "Borrower2FirstName": "",
      "Borrower2MiddleName": "",
      "Borrower2LastName": "",
      "Borrower1SSN__1": "",
      "Vesting": "",
      "Guarantor1FirstName": "",
      "Guarantor1MiddleName": "",
      "Guarantor1LastName": "",
      "Guarantor2FirstName": "",
      "Guarantor2MiddleName": "",
      "Guarantor2LastName": "",
      "AccountFirstName": "",
      "AccountMiddleName": "",
      "AccountLastName": "",
      "Closer": "",
      "CloserTitle": "",
      "CloserPhone": "",
      "PropType": "",
      "MailingAddress1": "",
      "MailingAddress2": "",
      "MailingCity": "",
      "MailingState": "",
      "MailingZip": "",
      "PropAddress1": "",
      "PropAddress2": "",
      "PropCity": "",
      "PropCounty": "",
      "PropState": "",
      "PropZip": "",
      "LoanType": "",
      "SalesPrice": "",
      "LoanAmount": "",
      "TotalCost": "",
      "LoanAmountTyped": "",
      "AppraisedAmount": "",
      "AppraisalPercent": "",
      "MaxLTV": "",
      "LoanTerm": "",
      "LoanTermMonths": "",
      "ConstructionTerm": "",
      "Amortization": "",
      "IOTerm": "",
      "InitialInterestRate": "",
      "Margin": "",
      "InterestRate": "",
      "Index": "",
      "FixedPeriod": "",
      "ClosingMonth": "",
      "InterestRateAdjustment": "",
      "Ceiling": "",
      "Floor": "",
      "PrepayTerm": "",
      "PrepayLimit": "",
      "AssumptionPercent": "",
      "LoanFeePercent": "",
      "DocFee": "",
      "CommitmentTerm": "",
      "LateCharge": "",
      "DefaultClauseRate": "",
      "DebtCoverageRatio": "",
      "CoverageAmount": "",
      "SignDate": "",
      "CommitmentFee": "",
      "AccountNo": "",
      "ArchitectName": "",
      "ArchitectCompany": "",
      "ArchitectAddressLine1": "",
      "ArchitectCity": "",
      "ArchitectState": "",
      "ArchitectZip": "",
      "Today": ""
    }
  ]

module.exports={
    docContants,
    OpenDBinfo
}
